services:
  pocketbase:
    image: ahmertahir/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    build:
      context: .
    ports:
      - "8090:8090"
    volumes:
      - ./pb_migrations:/pb/pb_migrations
      - ./pb_hooks:/pb/pb_hooks
      - ./pb_data:/pb/pb_data
volumes:
  pb_migrations:
  pb_hooks:
  pb_data:
