services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel_user
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: laravel
    volumes:
      - ./db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8080:80
  redis-stack-server:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./redis_data:/data
    restart: unless-stopped
volumes:
  db_data:
  redis_data: